import type { FinancialClassification, UnitOfMeasure } from "@prisma/client";

export type CatalogProduct = {
  name: string;
  categorySlug: string;
  subcategory: string;
  financialClassification: FinancialClassification;
  includeInFoodCost?: boolean;
  unit: UnitOfMeasure;
  sku: string;
  minQuantity: number;
  averageCost: number;
  supplier?: string;
  notes?: string;
  /** Conversiones para conteo físico (unidad → unidad base del producto). */
  countUnits?: {
    unit: UnitOfMeasure;
    conversionFactor: number;
    label?: string;
  }[];
};

export function defaultIncludeInFoodCost(
  classification: FinancialClassification
): boolean {
  return (
    classification === "FOOD_COST" || classification === "PACKAGING_COST"
  );
}

const FC = {
  FOOD: "FOOD_COST" as const,
  PKG: "PACKAGING_COST" as const,
  CLEAN: "CLEANING_SUPPLIES" as const,
  OPS: "OPERATING_SUPPLIES" as const,
};

function food(
  items: Omit<CatalogProduct, "financialClassification" | "includeInFoodCost">[]
): CatalogProduct[] {
  return items.map((item) => ({
    ...item,
    financialClassification: FC.FOOD,
    includeInFoodCost: true,
  }));
}

function packaging(
  items: Omit<CatalogProduct, "financialClassification" | "includeInFoodCost">[]
): CatalogProduct[] {
  return items.map((item) => ({
    ...item,
    financialClassification: FC.PKG,
    includeInFoodCost: true,
  }));
}

function cleaning(
  items: Omit<CatalogProduct, "financialClassification" | "includeInFoodCost">[]
): CatalogProduct[] {
  return items.map((item) => ({
    ...item,
    financialClassification: FC.CLEAN,
    includeInFoodCost: false,
  }));
}

function operating(
  items: Omit<CatalogProduct, "financialClassification" | "includeInFoodCost">[]
): CatalogProduct[] {
  return items.map((item) => ({
    ...item,
    financialClassification: FC.OPS,
    includeInFoodCost: false,
  }));
}

/** Catálogo inicial Açaí Factory — menús + operación real */
export const ACAI_FACTORY_CATALOG: CatalogProduct[] = [
  ...food([
    // Bases y sorbetes (menús Signature, Premium, Coco & Mango, Baby Bowls)
    {
      name: "Açaí pulpa congelada",
      categorySlug: "bases-sorbetes",
      subcategory: "Bases congeladas",
      unit: "BAG",
      sku: "FC-BAS-001",
      minQuantity: 10,
      averageCost: 12.5,
      supplier: "Distribuidora Tropical",
      notes: "Base principal bowls y smoothies",
      countUnits: [
        { unit: "LB", conversionFactor: 0.25, label: "Libras" },
        { unit: "CASE", conversionFactor: 20, label: "Manga" },
        { unit: "UNIT", conversionFactor: 1, label: "Each" },
        { unit: "BROKEN_CASE", conversionFactor: 10, label: "Broken box" },
        { unit: "BOX", conversionFactor: 5, label: "Box" },
      ],
    },
    {
      name: "Pitaya congelada",
      categorySlug: "bases-sorbetes",
      subcategory: "Bases congeladas",
      unit: "BAG",
      sku: "FC-BAS-002",
      minQuantity: 6,
      averageCost: 14.0,
      supplier: "Distribuidora Tropical",
    },
    {
      name: "Sorbete de mango",
      categorySlug: "bases-sorbetes",
      subcategory: "Sorbetes",
      unit: "GALLON",
      sku: "FC-BAS-003",
      minQuantity: 4,
      averageCost: 18.0,
      supplier: "Distribuidora Tropical",
      notes: "Coco & Mango Luxury, Tropical Summer",
    },
    {
      name: "Sorbete de coco",
      categorySlug: "bases-sorbetes",
      subcategory: "Sorbetes",
      unit: "GALLON",
      sku: "FC-BAS-004",
      minQuantity: 4,
      averageCost: 17.5,
      supplier: "Distribuidora Tropical",
      notes: "North Pole, Snow Coconut, Mini Coconut Bliss",
    },
    {
      name: "Aceite de coco",
      categorySlug: "bases-sorbetes",
      subcategory: "Aceites",
      unit: "GALLON",
      sku: "FC-BAS-005",
      minQuantity: 2,
      averageCost: 22.0,
      supplier: "Distribuidora Tropical",
    },
    {
      name: "Semillas de chía",
      categorySlug: "bases-sorbetes",
      subcategory: "Chia pudding",
      unit: "BAG",
      sku: "FC-BAS-006",
      minQuantity: 3,
      averageCost: 8.5,
      supplier: "Empaques del Norte",
      notes: "Chia puddings y bowl Iceberg",
    },
    {
      name: "Base preparada chia pudding",
      categorySlug: "bases-sorbetes",
      subcategory: "Chia pudding",
      unit: "GALLON",
      sku: "FC-BAS-007",
      minQuantity: 2,
      averageCost: 9.0,
      notes: "Pre-batch diario",
    },
    // Frutas frescas
    {
      name: "Guineo",
      categorySlug: "frutas",
      subcategory: "Frutas frescas",
      unit: "LB",
      sku: "FC-FRU-001",
      minQuantity: 20,
      averageCost: 0.85,
      supplier: "Frutas Frescas SA",
    },
    {
      name: "Fresa",
      categorySlug: "frutas",
      subcategory: "Frutas frescas",
      unit: "LB",
      sku: "FC-FRU-002",
      minQuantity: 12,
      averageCost: 3.2,
      supplier: "Frutas Frescas SA",
    },
    {
      name: "Mango",
      categorySlug: "frutas",
      subcategory: "Frutas frescas",
      unit: "LB",
      sku: "FC-FRU-003",
      minQuantity: 15,
      averageCost: 2.1,
      supplier: "Frutas Frescas SA",
    },
    {
      name: "Piña",
      categorySlug: "frutas",
      subcategory: "Frutas frescas",
      unit: "LB",
      sku: "FC-FRU-004",
      minQuantity: 10,
      averageCost: 1.4,
      supplier: "Frutas Frescas SA",
    },
    {
      name: "Kiwi",
      categorySlug: "frutas",
      subcategory: "Frutas frescas",
      unit: "LB",
      sku: "FC-FRU-005",
      minQuantity: 8,
      averageCost: 4.5,
      supplier: "Frutas Frescas SA",
    },
    {
      name: "Blueberry",
      categorySlug: "frutas",
      subcategory: "Frutas frescas",
      unit: "LB",
      sku: "FC-FRU-006",
      minQuantity: 6,
      averageCost: 5.8,
      supplier: "Frutas Frescas SA",
    },
    {
      name: "Cereza",
      categorySlug: "frutas",
      subcategory: "Frutas frescas",
      unit: "LB",
      sku: "FC-FRU-007",
      minQuantity: 5,
      averageCost: 6.2,
      supplier: "Frutas Frescas SA",
      notes: "Cherries Earthquake, Volcano Eruption",
    },
    {
      name: "Guayaba",
      categorySlug: "frutas",
      subcategory: "Frutas frescas",
      unit: "LB",
      sku: "FC-FRU-008",
      minQuantity: 5,
      averageCost: 2.8,
      supplier: "Frutas Frescas SA",
      notes: "North Pole bowl",
    },
    {
      name: "Frambuesa",
      categorySlug: "frutas",
      subcategory: "Frutas frescas",
      unit: "LB",
      sku: "FC-FRU-009",
      minQuantity: 4,
      averageCost: 7.5,
      supplier: "Frutas Frescas SA",
      notes: "Pistachio Crunch Chia",
    },
    // Toppings y granos
    {
      name: "Granola",
      categorySlug: "toppings",
      subcategory: "Secos",
      unit: "BAG",
      sku: "FC-TOP-001",
      minQuantity: 5,
      averageCost: 4.2,
      supplier: "Empaques del Norte",
    },
    {
      name: "Coco rallado",
      categorySlug: "toppings",
      subcategory: "Secos",
      unit: "BAG",
      sku: "FC-TOP-002",
      minQuantity: 4,
      averageCost: 3.8,
      supplier: "Empaques del Norte",
    },
    {
      name: "Malvavisco",
      categorySlug: "toppings",
      subcategory: "Secos",
      unit: "BAG",
      sku: "FC-TOP-003",
      minQuantity: 3,
      averageCost: 5.5,
      supplier: "Empaques del Norte",
    },
    {
      name: "Arándanos secos",
      categorySlug: "toppings",
      subcategory: "Secos",
      unit: "BAG",
      sku: "FC-TOP-004",
      minQuantity: 2,
      averageCost: 6.0,
      supplier: "Empaques del Norte",
      notes: "Volcano Eruption",
    },
    {
      name: "Chips de chocolate blanco",
      categorySlug: "toppings",
      subcategory: "Secos",
      unit: "BAG",
      sku: "FC-TOP-005",
      minQuantity: 2,
      averageCost: 7.2,
      supplier: "Empaques del Norte",
    },
    {
      name: "Chips de chocolate",
      categorySlug: "toppings",
      subcategory: "Secos",
      unit: "BAG",
      sku: "FC-TOP-006",
      minQuantity: 2,
      averageCost: 6.8,
      supplier: "Empaques del Norte",
    },
    {
      name: "Pistachos",
      categorySlug: "toppings",
      subcategory: "Secos",
      unit: "LB",
      sku: "FC-TOP-007",
      minQuantity: 3,
      averageCost: 12.0,
      supplier: "Empaques del Norte",
    },
    {
      name: "Maní",
      categorySlug: "toppings",
      subcategory: "Secos",
      unit: "LB",
      sku: "FC-TOP-008",
      minQuantity: 3,
      averageCost: 4.5,
      supplier: "Empaques del Norte",
      notes: "Bowl Iceberg, add-on",
    },
    {
      name: "Galletas Oreo",
      categorySlug: "snacks",
      subcategory: "Galletas y dulces",
      unit: "PACK",
      sku: "FC-SNK-001",
      minQuantity: 4,
      averageCost: 3.5,
      notes: "Milkshakes, frappés, Oreo Chia",
    },
    {
      name: "Galletas Biscoff",
      categorySlug: "snacks",
      subcategory: "Galletas y dulces",
      unit: "PACK",
      sku: "FC-SNK-002",
      minQuantity: 3,
      averageCost: 4.2,
      notes: "Bowl Lotus, topping Biscoff",
    },
    {
      name: "M&M's",
      categorySlug: "snacks",
      subcategory: "Galletas y dulces",
      unit: "PACK",
      sku: "FC-SNK-003",
      minQuantity: 3,
      averageCost: 2.8,
      notes: "Frappé M&M's",
    },
    {
      name: "Twix",
      categorySlug: "snacks",
      subcategory: "Galletas y dulces",
      unit: "PACK",
      sku: "FC-SNK-004",
      minQuantity: 3,
      averageCost: 2.5,
    },
    {
      name: "Kit Kat",
      categorySlug: "snacks",
      subcategory: "Galletas y dulces",
      unit: "PACK",
      sku: "FC-SNK-005",
      minQuantity: 3,
      averageCost: 2.5,
    },
    // Salsas y cremas
    {
      name: "Nutella",
      categorySlug: "salsas-cremas",
      subcategory: "Untables",
      unit: "JAR",
      sku: "FC-SAL-001",
      minQuantity: 4,
      averageCost: 8.5,
      supplier: "Empaques del Norte",
    },
    {
      name: "Mantequilla de maní",
      categorySlug: "salsas-cremas",
      subcategory: "Untables",
      unit: "JAR",
      sku: "FC-SAL-002",
      minQuantity: 3,
      averageCost: 6.0,
      notes: "Mini Power Bowl, add-on",
    },
    {
      name: "Mantequilla de almendra",
      categorySlug: "salsas-cremas",
      subcategory: "Untables",
      unit: "JAR",
      sku: "FC-SAL-003",
      minQuantity: 2,
      averageCost: 9.5,
      notes: "Add-on menú",
    },
    {
      name: "Crema de pistacho",
      categorySlug: "salsas-cremas",
      subcategory: "Cremas",
      unit: "JAR",
      sku: "FC-SAL-004",
      minQuantity: 2,
      averageCost: 11.0,
      notes: "Rainstorm bowl, Pistachio Crunch Chia",
    },
    {
      name: "Crema cheesecake",
      categorySlug: "salsas-cremas",
      subcategory: "Cremas",
      unit: "GALLON",
      sku: "FC-SAL-005",
      minQuantity: 2,
      averageCost: 14.0,
      notes: "Strawberry Cheesecake Chia",
    },
    {
      name: "Crema de coco",
      categorySlug: "salsas-cremas",
      subcategory: "Cremas",
      unit: "GALLON",
      sku: "FC-SAL-006",
      minQuantity: 2,
      averageCost: 12.0,
      notes: "Mango Paradise Chia",
    },
    {
      name: "Crema Biscoff",
      categorySlug: "salsas-cremas",
      subcategory: "Cremas",
      unit: "JAR",
      sku: "FC-SAL-007",
      minQuantity: 2,
      averageCost: 10.5,
    },
    {
      name: "Miel de agave",
      categorySlug: "salsas-cremas",
      subcategory: "Endulzantes",
      unit: "GALLON",
      sku: "FC-SAL-008",
      minQuantity: 2,
      averageCost: 15.0,
      notes: "Mini Tropical Storm",
    },
    {
      name: "Jarabe de caramelo",
      categorySlug: "salsas-cremas",
      subcategory: "Jarabes",
      unit: "GALLON",
      sku: "FC-SAL-009",
      minQuantity: 2,
      averageCost: 11.0,
      notes: "Caramel Kisses milkshake",
    },
    {
      name: "Salsa de chocolate blanco",
      categorySlug: "salsas-cremas",
      subcategory: "Jarabes",
      unit: "GALLON",
      sku: "FC-SAL-010",
      minQuantity: 2,
      averageCost: 12.5,
      notes: "Bowl Sunny",
    },
    {
      name: "Crema batida",
      categorySlug: "salsas-cremas",
      subcategory: "Cremas",
      unit: "GALLON",
      sku: "FC-SAL-011",
      minQuantity: 3,
      averageCost: 8.0,
      notes: "Milkshakes, frappés, Volcano Eruption",
    },
    {
      name: "Crema marshmallow",
      categorySlug: "salsas-cremas",
      subcategory: "Cremas",
      unit: "GALLON",
      sku: "FC-SAL-012",
      minQuantity: 2,
      averageCost: 9.5,
      notes: "Bowl Lotus",
    },
    {
      name: "Cacao en polvo",
      categorySlug: "salsas-cremas",
      subcategory: "Polvos",
      unit: "BAG",
      sku: "FC-SAL-013",
      minQuantity: 2,
      averageCost: 7.0,
      notes: "Oreo Nutella Chia",
    },
    // Lácteos y bebidas base
    {
      name: "Leche entera",
      categorySlug: "lacteos-bebidas",
      subcategory: "Lácteos",
      unit: "GALLON",
      sku: "FC-LAC-001",
      minQuantity: 4,
      averageCost: 5.5,
      supplier: "Distribuidora Tropical",
    },
    {
      name: "Leche de almendra",
      categorySlug: "lacteos-bebidas",
      subcategory: "Lácteos alternativos",
      unit: "GALLON",
      sku: "FC-LAC-002",
      minQuantity: 2,
      averageCost: 7.5,
    },
    {
      name: "Leche de avena",
      categorySlug: "lacteos-bebidas",
      subcategory: "Lácteos alternativos",
      unit: "GALLON",
      sku: "FC-LAC-003",
      minQuantity: 2,
      averageCost: 7.0,
    },
    {
      name: "Helado de vainilla",
      categorySlug: "lacteos-bebidas",
      subcategory: "Helados",
      unit: "GALLON",
      sku: "FC-LAC-004",
      minQuantity: 3,
      averageCost: 16.0,
      notes: "Base milkshakes",
    },
    {
      name: "Polvo de proteína",
      categorySlug: "lacteos-bebidas",
      subcategory: "Suplementos",
      unit: "BAG",
      sku: "FC-LAC-005",
      minQuantity: 2,
      averageCost: 28.0,
      notes: "Add-on menú",
    },
    // Café y chocolate
    {
      name: "Café en grano",
      categorySlug: "cafe-chocolate",
      subcategory: "Café",
      unit: "LB",
      sku: "FC-CAF-001",
      minQuantity: 5,
      averageCost: 9.5,
      supplier: "Distribuidora Tropical",
      notes: "Hot coffee, mocha, cappuccino, frappés",
    },
    {
      name: "Mezcla chocolate caliente",
      categorySlug: "cafe-chocolate",
      subcategory: "Chocolate",
      unit: "BAG",
      sku: "FC-CAF-002",
      minQuantity: 3,
      averageCost: 12.0,
      notes: "Hot chocolate $1.85",
    },
    {
      name: "Jarabe de chocolate",
      categorySlug: "cafe-chocolate",
      subcategory: "Jarabes",
      unit: "GALLON",
      sku: "FC-CAF-003",
      minQuantity: 2,
      averageCost: 10.0,
      notes: "Mocha, Chocolate Passion",
    },
    {
      name: "Canela en polvo",
      categorySlug: "cafe-chocolate",
      subcategory: "Especias",
      unit: "JAR",
      sku: "FC-CAF-004",
      minQuantity: 1,
      averageCost: 4.0,
      notes: "Cappuccino topping",
    },
  ]),
  ...packaging([
    {
      name: "Bowl 8 oz (mini)",
      categorySlug: "empaques",
      subcategory: "Bowls",
      unit: "BOX",
      sku: "PK-BWL-008",
      minQuantity: 3,
      averageCost: 14.0,
      supplier: "Empaques del Norte",
      notes: "Baby Açaí Bowls, Chia Puddings $4.25-$5",
    },
    {
      name: "Bowl 16 oz (SM)",
      categorySlug: "empaques",
      subcategory: "Bowls",
      unit: "BOX",
      sku: "PK-BWL-016",
      minQuantity: 4,
      averageCost: 18.0,
      supplier: "Empaques del Norte",
      notes: "Signature SM $8.99, Premium SM $9.99",
    },
    {
      name: "Bowl 24 oz (LG)",
      categorySlug: "empaques",
      subcategory: "Bowls",
      unit: "BOX",
      sku: "PK-BWL-024",
      minQuantity: 4,
      averageCost: 22.0,
      supplier: "Empaques del Norte",
      notes: "Signature LG $10.99, Premium LG $11.99",
    },
    {
      name: "Tapa bowl domo",
      categorySlug: "empaques",
      subcategory: "Tapas",
      unit: "BOX",
      sku: "PK-TAP-001",
      minQuantity: 3,
      averageCost: 8.0,
      supplier: "Empaques del Norte",
    },
    {
      name: "Vaso 16 oz",
      categorySlug: "empaques",
      subcategory: "Vasos",
      unit: "BOX",
      sku: "PK-VAS-016",
      minQuantity: 4,
      averageCost: 16.0,
      supplier: "Empaques del Norte",
      notes: "Smoothies, frappés",
    },
    {
      name: "Vaso 24 oz",
      categorySlug: "empaques",
      subcategory: "Vasos",
      unit: "BOX",
      sku: "PK-VAS-024",
      minQuantity: 3,
      averageCost: 20.0,
      supplier: "Empaques del Norte",
    },
    {
      name: "Tapa vaso domo",
      categorySlug: "empaques",
      subcategory: "Tapas",
      unit: "BOX",
      sku: "PK-TAP-002",
      minQuantity: 3,
      averageCost: 9.0,
      supplier: "Empaques del Norte",
      notes: "Bebidas con crema batida",
    },
    {
      name: "Tapa vaso plana",
      categorySlug: "empaques",
      subcategory: "Tapas",
      unit: "BOX",
      sku: "PK-TAP-003",
      minQuantity: 3,
      averageCost: 7.5,
      supplier: "Empaques del Norte",
    },
    {
      name: "Vaso café caliente 12 oz",
      categorySlug: "empaques",
      subcategory: "Vasos café",
      unit: "BOX",
      sku: "PK-CAF-012",
      minQuantity: 2,
      averageCost: 12.0,
      supplier: "Empaques del Norte",
    },
    {
      name: "Vaso café caliente 16 oz",
      categorySlug: "empaques",
      subcategory: "Vasos café",
      unit: "BOX",
      sku: "PK-CAF-016",
      minQuantity: 2,
      averageCost: 14.0,
      supplier: "Empaques del Norte",
    },
    {
      name: "Tapa café",
      categorySlug: "empaques",
      subcategory: "Tapas",
      unit: "BOX",
      sku: "PK-TAP-004",
      minQuantity: 2,
      averageCost: 6.0,
      supplier: "Empaques del Norte",
    },
    {
      name: "Sleeve café",
      categorySlug: "empaques",
      subcategory: "Portavasos",
      unit: "BOX",
      sku: "PK-SLV-001",
      minQuantity: 2,
      averageCost: 8.0,
      supplier: "Empaques del Norte",
    },
    {
      name: "Sorbeto grueso",
      categorySlug: "empaques",
      subcategory: "Sorbetos",
      unit: "BOX",
      sku: "PK-SOR-001",
      minQuantity: 3,
      averageCost: 10.0,
      supplier: "Empaques del Norte",
      notes: "Smoothies y milkshakes",
    },
    {
      name: "Sorbeto estándar",
      categorySlug: "empaques",
      subcategory: "Sorbetos",
      unit: "BOX",
      sku: "PK-SOR-002",
      minQuantity: 2,
      averageCost: 7.0,
      supplier: "Empaques del Norte",
    },
    {
      name: "Cuchara plástica",
      categorySlug: "empaques",
      subcategory: "Utensilios",
      unit: "BOX",
      sku: "PK-UTL-001",
      minQuantity: 3,
      averageCost: 6.5,
      supplier: "Empaques del Norte",
    },
    {
      name: "Servilleta",
      categorySlug: "empaques",
      subcategory: "Utensilios",
      unit: "BOX",
      sku: "PK-UTL-002",
      minQuantity: 3,
      averageCost: 5.0,
      supplier: "Empaques del Norte",
    },
    {
      name: "Portavasos 2 unidades",
      categorySlug: "empaques",
      subcategory: "Portavasos",
      unit: "BOX",
      sku: "PK-CRR-002",
      minQuantity: 2,
      averageCost: 11.0,
      supplier: "Empaques del Norte",
    },
    {
      name: "Portavasos 4 unidades",
      categorySlug: "empaques",
      subcategory: "Portavasos",
      unit: "BOX",
      sku: "PK-CRR-004",
      minQuantity: 2,
      averageCost: 14.0,
      supplier: "Empaques del Norte",
    },
    {
      name: "Bolsa para llevar",
      categorySlug: "empaques",
      subcategory: "Bolsas",
      unit: "BOX",
      sku: "PK-BOL-001",
      minQuantity: 2,
      averageCost: 9.0,
      supplier: "Empaques del Norte",
      notes: "Delivery y to-go",
    },
    {
      name: "Sticker logo Açaí Factory",
      categorySlug: "empaques",
      subcategory: "Branding",
      unit: "PACK",
      sku: "PK-BRD-001",
      minQuantity: 2,
      averageCost: 15.0,
      supplier: "Empaques del Norte",
      notes: "Cada bowl mini en menú",
    },
    {
      name: "Etiqueta orden",
      categorySlug: "empaques",
      subcategory: "Branding",
      unit: "ROLL",
      sku: "PK-BRD-002",
      minQuantity: 2,
      averageCost: 12.0,
      supplier: "Empaques del Norte",
    },
  ]),
  ...cleaning([
    {
      name: "Jabón de manos",
      categorySlug: "limpieza",
      subcategory: "Higiene",
      unit: "GALLON",
      sku: "CL-HIG-001",
      minQuantity: 2,
      averageCost: 8.0,
      supplier: "Suministros Limpieza PR",
    },
    {
      name: "Jabón para platos",
      categorySlug: "limpieza",
      subcategory: "Cocina",
      unit: "GALLON",
      sku: "CL-COC-001",
      minQuantity: 2,
      averageCost: 9.5,
      supplier: "Suministros Limpieza PR",
    },
    {
      name: "Sanitizer (desinfectante manos)",
      categorySlug: "limpieza",
      subcategory: "Higiene",
      unit: "GALLON",
      sku: "CL-HIG-002",
      minQuantity: 2,
      averageCost: 11.0,
      supplier: "Suministros Limpieza PR",
    },
    {
      name: "Sanitizer superficies",
      categorySlug: "limpieza",
      subcategory: "Cocina",
      unit: "GALLON",
      sku: "CL-COC-002",
      minQuantity: 2,
      averageCost: 12.0,
      supplier: "Suministros Limpieza PR",
      notes: "Mesas prep, licuadoras",
    },
    {
      name: "Cloro",
      categorySlug: "limpieza",
      subcategory: "Desinfección",
      unit: "GALLON",
      sku: "CL-DES-001",
      minQuantity: 2,
      averageCost: 4.5,
      supplier: "Suministros Limpieza PR",
    },
    {
      name: "Limpiador multiusos",
      categorySlug: "limpieza",
      subcategory: "Superficies",
      unit: "GALLON",
      sku: "CL-SUP-001",
      minQuantity: 2,
      averageCost: 7.0,
      supplier: "Suministros Limpieza PR",
    },
    {
      name: "Degrasante cocina",
      categorySlug: "limpieza",
      subcategory: "Cocina",
      unit: "GALLON",
      sku: "CL-COC-003",
      minQuantity: 2,
      averageCost: 10.0,
      supplier: "Suministros Limpieza PR",
    },
    {
      name: "Bolsas de basura 33 gal",
      categorySlug: "limpieza",
      subcategory: "Desechos",
      unit: "BOX",
      sku: "CL-DES-002",
      minQuantity: 2,
      averageCost: 14.0,
      supplier: "Suministros Limpieza PR",
    },
    {
      name: "Guantes de limpieza",
      categorySlug: "limpieza",
      subcategory: "Protección",
      unit: "BOX",
      sku: "CL-PRO-001",
      minQuantity: 2,
      averageCost: 8.0,
      supplier: "Suministros Limpieza PR",
    },
    {
      name: "Papel industrial",
      categorySlug: "limpieza",
      subcategory: "Papel",
      unit: "ROLL",
      sku: "CL-PAP-001",
      minQuantity: 4,
      averageCost: 3.5,
      supplier: "Suministros Limpieza PR",
    },
  ]),
  ...operating([
    {
      name: "Guantes nitrilo (servicio)",
      categorySlug: "operativos",
      subcategory: "Protección",
      unit: "BOX",
      sku: "OP-PRO-001",
      minQuantity: 3,
      averageCost: 9.0,
      supplier: "Suministros Limpieza PR",
    },
    {
      name: "Uniforme polo",
      categorySlug: "operativos",
      subcategory: "Uniformes",
      unit: "UNIT",
      sku: "OP-UNI-001",
      minQuantity: 4,
      averageCost: 18.0,
      notes: "Por empleado",
    },
    {
      name: "Gorra Açaí Factory",
      categorySlug: "operativos",
      subcategory: "Uniformes",
      unit: "UNIT",
      sku: "OP-UNI-002",
      minQuantity: 4,
      averageCost: 12.0,
    },
    {
      name: "Marcador permanente",
      categorySlug: "operativos",
      subcategory: "Oficina",
      unit: "PACK",
      sku: "OP-OFC-001",
      minQuantity: 2,
      averageCost: 5.0,
      notes: "Marcar vasos y prep",
    },
    {
      name: "Cinta adhesiva",
      categorySlug: "operativos",
      subcategory: "Oficina",
      unit: "UNIT",
      sku: "OP-OFC-002",
      minQuantity: 2,
      averageCost: 4.0,
    },
    {
      name: "Botella squeeze 16 oz",
      categorySlug: "operativos",
      subcategory: "Prep",
      unit: "UNIT",
      sku: "OP-PRE-001",
      minQuantity: 6,
      averageCost: 3.5,
      notes: "Salsas en línea",
    },
    {
      name: "Contenedor prep 1/6",
      categorySlug: "operativos",
      subcategory: "Prep",
      unit: "UNIT",
      sku: "OP-PRE-002",
      minQuantity: 8,
      averageCost: 6.0,
      notes: "Toppings en línea",
    },
    {
      name: "Cuchillo prep frutas",
      categorySlug: "operativos",
      subcategory: "Herramientas",
      unit: "UNIT",
      sku: "OP-HER-001",
      minQuantity: 2,
      averageCost: 15.0,
    },
    {
      name: "Material POP menú",
      categorySlug: "operativos",
      subcategory: "Marketing",
      unit: "UNIT",
      sku: "OP-MKT-001",
      minQuantity: 1,
      averageCost: 45.0,
      notes: "Señalización mostrador",
    },
    {
      name: "Papel térmico recibos",
      categorySlug: "operativos",
      subcategory: "POS",
      unit: "ROLL",
      sku: "OP-POS-001",
      minQuantity: 4,
      averageCost: 4.5,
    },
  ]),
];
